version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: railway
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://postgres:postgres123@postgres:5432/railway
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PORT: 8080
    depends_on:
      postgres:
        condition: service_healthy
    command: uvicorn api.index:app --host 0.0.0.0 --port 8080 --reload

volumes:
  postgres_data: